function result = runSingleExperiment(scenario)
%RUNSINGLEEXPERIMENT Выполняет один запуск: RRT + minimum-snap + динамика.

    geometry.validateScenario( ...
        scenario.map, scenario.start2d, scenario.goal2d, ...
        scenario.obstacles, scenario.safetyRadius);

    params = scenario.rrt;
    if params.goalThreshold <= 0
        params.goalThreshold = params.stepSize;
    end

    startTime = tic;
    [path, tree] = rrt.plan( ...
        scenario.start2d, scenario.goal2d, scenario.map, ...
        scenario.obstacles, scenario.safetyRadius, params);
    calculationTime = toc(startTime);

    result.tree = tree;
    result.rawPath = path;
    result.rrtPath = [];
    result.path = [];
    result.referenceTrajectory = [];
    result.simLog = [];
    result.pathFound = ~isempty(path);
    result.calculationTime = calculationTime;
    result.message = '';

    if isempty(path)
        result.metrics = struct( ...
            'pathLength', NaN, ...
            'maxCurvature', NaN, ...
            'meanCurvature', NaN, ...
            'densePath', []);
        result.summary = makeSummary(result, []);
        result.message = 'Маршрут не найден.';
        return;
    end

    smoothPath = rrt.shortcutSmoothPath( ...
        path, scenario.map, scenario.obstacles, scenario.safetyRadius, ...
        params.collisionCheckStep, params.smoothingIterations);

    result.rrtPath = smoothPath;
    [result.simLog, result.referenceTrajectory] = quadrotor.simulateOnPath( ...
        smoothPath, scenario.quad, scenario.ctrl, scenario.sim);
    result.path = result.referenceTrajectory.xd(1:2, :)';
    result.metrics = metrics.pathMetrics(result.path, params.densePathStep);
    result.summary = makeSummary(result, result.simLog);
    result.message = 'Маршрут найден, minimum-snap траектория построена, моделирование выполнено.';
end

function summary = makeSummary(result, simLog)
%MAKESUMMARY Формирует табличную строку с итоговыми метриками.

    if isempty(simLog)
        dynamicFeasible = false;
        finalTrackingError = NaN;
        maxTrackingError = NaN;
        maxMotorThrust = NaN;
        meanMotorThrust = NaN;
    else
        dynamicFeasible = simLog.dynamicFeasible;
        finalTrackingError = simLog.finalTrackingError;
        maxTrackingError = simLog.maxTrackingError;
        maxMotorThrust = simLog.maxMotorThrust;
        meanMotorThrust = simLog.meanMotorThrust;
    end

    summary = table( ...
        result.pathFound, ...
        result.calculationTime, ...
        result.metrics.pathLength, ...
        result.metrics.maxCurvature, ...
        result.metrics.meanCurvature, ...
        dynamicFeasible, ...
        finalTrackingError, ...
        maxTrackingError, ...
        maxMotorThrust, ...
        meanMotorThrust, ...
        'VariableNames', { ...
        'PathFound', ...
        'CalculationTime_s', ...
        'PathLength_m', ...
        'MaxCurvature_1_m', ...
        'MeanCurvature_1_m', ...
        'DynamicFeasible', ...
        'FinalTrackingError_m', ...
        'MaxTrackingError_m', ...
        'MaxMotorThrust_N', ...
        'MeanMotorThrust_N'});
end
